import { type NextPage } from "next";
import Head from "next/head";
import Card from "~/components/Card";
import Navigation from "~/components/Nav";
import Skeleton from "~/components/Skeleton";
import Suspense from "~/components/Suspense";
import { api } from "~/utils/api";

const Fallback = () => (
  <>
    <Skeleton />
    <Skeleton />
    <Skeleton />
  </>
);

const Home: NextPage = () => {
  const { data, isSuccess } = api.task.getAll.useQuery();

  return (
    <>
      <Head>
        <title>To Do or Not</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation />
      </header>
      <main className="mx-auto max-w-4xl px-4">
        <h1 className="text-3xl font-bold">To Do or Not</h1>
        <section className="grid grid-cols-1 gap-2 sm:grid-cols-2">
          <Suspense isFallback={!isSuccess} fallback={<Fallback />}>
            {data?.map((task) => (
              <Card
                key={task.id}
                id={task.id}
                title={task.title}
                done={task.completed}
              >
                {task.description}
              </Card>
            ))}
          </Suspense>
          {/* <Fallback/> */}
        </section>
      </main>
    </>
  );
};

export default Home;
